version: "2"

services:
  rosmaster:
    container_name: rosmaster
    image: ros:melodic-ros-base-stretch
    command: roscore
    ports: 
      - "11311:11311"

  mosaic_driver:
    container_name: mosaic_driver
    build: 
      context: .
      dockerfile: melodic.Dockerfile
    command: tail -F /dev/null
    volumes: 
        - ./mosaic_gnss_driver:/catkin_ws/src/mosaic_gnss_driver
    environment:
      - "ROS_MASTER_URI=http://rosmaster:11311"
    depends_on:
      - rosmaster
